name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.0

      - name: Use Go 1.13
        uses: actions/setup-go@v1
        with:
            go-version: 1.13.x

      - name: Build game
        run: |
          git clone https://github.com/tmedwards/tweego.git
          export PATH=$PATH:$(go env GOPATH)/bin
          cd tweego
          go get
          go install
          cd ../
          mkdir dist
          tweego were.twee -o dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
